version: 2

jobs:
  build:
    working_directory: ~/launchpad

    docker:
      - image: circleci/node:8

    steps:
      - setup_remote_docker
      - checkout

      # run build test
      - run: .circleci/build.sh

      # deploy the build (if on a deployment branch)
      - deploy:
          name: Docker Image Deploment
          command: .circleci/deploy.sh
